[package]
name = "callbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper_req_exts = "0.10.0"
lazy_static = "1.4.0"
regex = "1.7.1"
reqwest = "0.11.14"
tokio = { version = "1.24.2", features = ["macros", "full"] }
